/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/L624ANjsMo9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import Link from 'next/link'

export function Chat() {
  return (
    <div className="mx-auto flex h-screen w-full max-w-4xl">
      <div className="flex w-[300px] flex-col border-r bg-muted/20 p-4">
        <div className="mb-4 flex items-center justify-between">
          <div className="text-lg font-medium">Chats</div>
          <Button variant="ghost" size="icon" className="rounded-full">
            <PlusIcon className="h-5 w-5" />
            <span className="sr-only">New chat</span>
          </Button>
        </div>
        <div className="relative mb-4">
          <SearchIcon className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search chats"
            className="h-9 pl-9 text-sm"
          />
        </div>
        <ScrollArea className="flex-1">
          <div className="space-y-2">
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md p-2 hover:bg-muted/50"
              prefetch={false}
            >
              <Avatar className="h-10 w-10 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Image" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="truncate font-medium">John Doe</div>
                <div className="truncate text-sm text-muted-foreground">
                  Hey, how's it going?
                </div>
              </div>
              <div className="text-xs text-muted-foreground">2:30 PM</div>
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md p-2 hover:bg-muted/50"
              prefetch={false}
            >
              <Avatar className="h-10 w-10 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Image" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="truncate font-medium">Jane Smith</div>
                <div className="truncate text-sm text-muted-foreground">
                  Did you see the new update?
                </div>
              </div>
              <div className="text-xs text-muted-foreground">12:45 PM</div>
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md p-2 hover:bg-muted/50"
              prefetch={false}
            >
              <Avatar className="h-10 w-10 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Image" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="truncate font-medium">Alex Johnson</div>
                <div className="truncate text-sm text-muted-foreground">
                  Sounds good, let's do it!
                </div>
              </div>
              <div className="text-xs text-muted-foreground">9:00 AM</div>
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md p-2 hover:bg-muted/50"
              prefetch={false}
            >
              <Avatar className="h-10 w-10 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Image" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="truncate font-medium">Sarah Lee</div>
                <div className="truncate text-sm text-muted-foreground">
                  I'll be there in 10 minutes.
                </div>
              </div>
              <div className="text-xs text-muted-foreground">Yesterday</div>
            </Link>
          </div>
        </ScrollArea>
      </div>
      <div className="flex flex-1 flex-col">
        <div className="flex items-center gap-3 border-b p-4">
          <Avatar className="h-10 w-10 border">
            <AvatarImage src="/placeholder-user.jpg" alt="Image" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div>
            <div className="font-medium">John Doe</div>
            <div className="text-xs text-muted-foreground">Online</div>
          </div>
          <div className="ml-auto flex items-center gap-2">
            <Button variant="ghost" size="icon">
              <PhoneIcon className="h-5 w-5" />
              <span className="sr-only">Call</span>
            </Button>
            <Button variant="ghost" size="icon">
              <VideoIcon className="h-5 w-5" />
              <span className="sr-only">Video call</span>
            </Button>
            <Button variant="ghost" size="icon">
              <MoveHorizontalIcon className="h-5 w-5" />
              <span className="sr-only">More options</span>
            </Button>
          </div>
        </div>
        <ScrollArea className="flex-1 space-y-4 p-4">
          <div className="flex items-end gap-2">
            <Avatar className="h-8 w-8 border">
              <AvatarImage src="/placeholder-user.jpg" alt="Image" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="max-w-[65%] rounded-lg bg-muted p-3 text-sm">
              Hey, how's it going? I wanted to check in and see if you had any
              updates on the project.
            </div>
            <div className="text-xs text-muted-foreground">3:45 PM</div>
          </div>
          <div className="flex items-end justify-end gap-2">
            <div className="max-w-[65%] rounded-lg bg-primary p-3 text-sm text-primary-foreground">
              The project is going well! I've made some good progress on the
              design and I'm ready to share an update with the team.
            </div>
            <div className="text-xs text-muted-foreground">3:47 PM</div>
          </div>
          <div className="flex items-end gap-2">
            <Avatar className="h-8 w-8 border">
              <AvatarImage src="/placeholder-user.jpg" alt="Image" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="max-w-[65%] rounded-lg bg-muted p-3 text-sm">
              Great, let's schedule a meeting to discuss the updates. I'm free
              this afternoon if that works for you.
            </div>
            <div className="text-xs text-muted-foreground">3:50 PM</div>
          </div>
          <div className="flex items-end justify-end gap-2">
            <div className="max-w-[65%] rounded-lg bg-primary p-3 text-sm text-primary-foreground">
              Sounds good, let's meet at 4pm. I'll send a calendar invite.
            </div>
            <div className="text-xs text-muted-foreground">3:51 PM</div>
          </div>
        </ScrollArea>
        <div className="flex items-center gap-2 border-t p-3">
          <Button variant="ghost" size="icon">
            <PaperclipIcon className="h-5 w-5" />
            <span className="sr-only">Attach file</span>
          </Button>
          <Input
            type="text"
            placeholder="Type your message..."
            className="flex-1"
          />
          <Button variant="ghost" size="icon">
            <SendIcon className="h-5 w-5" />
            <span className="sr-only">Send message</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

function MoveHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}

function PaperclipIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48" />
    </svg>
  )
}

function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}

function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}
